load ../data/cleandata_sce.mat
sce=sce.selectcells(sce.c_cell_cycle_tx=="G1");
x=sce.list_cell_attributes{2};
y=sce.c_cell_type_tx;
a=["WT";"KO"];
T=table(x,y,a(sce.c_batch_id));

%%
cLorder=["Noncycling SC",...
    "Cycling SC", ...
    "TA",...
    "EEC",...
    "EC",...
    "Tuft cell",...
    "DCS (type 2)",...
    "DCS (type 1)",...
    "Goblet (type 2)",...
    "Goblet (type 1)"];

pkg.i_violinplot_groupordered(x,y,cLorder)
% writetable(T,'potency_G1phase.csv');
xlim([0 11])
c1=sce.c_cell_type_tx;
c2=a(sce.c_batch_id);
[c,cx1,cx2] = findgroups(c1,c2);
cL=strcat(cx1," ",cx2);
%%
% cLorder=["TA WT", "TA KO", "Cycling SC WT", "Cycling SC KO", ...
%     "Noncycling SC WT", "Noncycling SC KO", "EC WT", "EC KO",...
%     "EEC WT", "EEC KO", "Tuft cell WT", "Tuft cell KO",...
%     "DCS (type 2) WT", "DCS (type 2) KO",...
%     "Goblet (type 2) WT", "Goblet (type 2) KO",...
%     "DCS (type 1) WT", "DCS (type 1) KO", "Goblet (type 1) WT", "Goblet (type 1) KO"];
% 

cLorder=["Noncycling SC WT", "Noncycling SC KO",... 
    "Cycling SC WT", "Cycling SC KO", ...
    "TA WT", "TA KO",...
    "EEC WT", "EEC KO","EC WT", "EC KO",...
    "Tuft cell WT", "Tuft cell KO",...
    "DCS (type 2) WT", "DCS (type 2) KO",...
    "DCS (type 1) WT", "DCS (type 1) KO",...
    "Goblet (type 2) WT", "Goblet (type 2) KO",...
    "Goblet (type 1) WT", "Goblet (type 1) KO"];


h=figure;
p=pkg.i_violinplot_groupordered(x,cL(c),cLorder,true);
% a=0.5+(2:2:20);
% for k=1:length(a)
% xline(a(k))
% end
for k=1:2:20
    p(k).ViolinColor=p(k+1).ViolinColor;
end
h.Position(3)=h.Position(3)*2;
xlim([0 21])
%%